HotelMVC/Models/Orders.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HotelMVC_TONE.Models
{
	public class Orders
	{
		public int Id { get; set; }
		[DisplayName("Order Id#")]
		public int orderId { get; set; }
		public int userId { get; set; }
		public int itemId { get; set; }
		[DataType(DataType.Currency)]
		public decimal price { get; set; }
		[Range(0, 20, ErrorMessage = "Please select Number within (0,20)")]
		public int quantity { get; set; }
		public DateTime dop { get; set; }

	}
}

HotelMVC/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HotelMVC_TONE.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;

namespace HotelMVC_TONE.Controllers
{
	public class ItemsController : Controller
	{
		public override void OnActionExecuting(ActionExecutingContext filterContext)
		{
			if (SessionWrapper.userId == -1)
			{
				filterContext.Result = RedirectToAction("Index", "Users");
			}
		}

		// GET: Items
		public ViewResult Index()
		{
			IEnumerable<Item> items = null;
			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.BaseAddress = new Uri("http://localhost:5000/api/");
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					//HTTP GET item list
					var responseTask = client.GetAsync("items");
					responseTask.Wait();

					var result = responseTask.Result;
					if (result.IsSuccessStatusCode)
					{
						var readTask = result.Content.ReadAsAsync<IList<Item>>();
						readTask.Wait();

						items = readTask.Result;
					}
					else
					{
						items = Enumerable.Empty<Item>();

						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
			}
			return View(items);
		}

		// GET: Items/Details/id
		public ActionResult Details(int? id)
		{
			Item item = null;
			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{

					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					//HTTP GET item list
					var responseTask = client.GetAsync("http://localhost:5000/api/items/" + id);
					responseTask.Wait();

					var result = responseTask.Result;
					if (result.IsSuccessStatusCode)
					{
						var readTask = result.Content.ReadAsAsync<Item>();
						readTask.Wait();

						item = readTask.Result;
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}

				return View(item);
			}
		}

		// GET: Items/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Items/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[AllowAnonymous]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Title,Category,Description,Price")] Item item)
		{
			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.BaseAddress = new Uri("http://localhost:5000/api/");
					client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					var response = await client.PostAsJsonAsync<Item>("items", item);

					if (response.IsSuccessStatusCode)
					{
						var retVal = await response.Content.ReadAsAsync<Item>();
						return RedirectToAction("Details", new { id = retVal.Id });
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
				return RedirectToAction(nameof(Index));
			}
		}

		// GET: Items/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{

			Item item = null;

			if (SessionWrapper.role != 1)
			{
				ModelState.AddModelError(string.Empty, "Access Denied. Only available to admin");
				return View(item);
			}

			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					var responseTask = client.GetAsync("http://localhost:5000/api/items/" + id);
					responseTask.Wait();

					var result = responseTask.Result;
					if (result.IsSuccessStatusCode)
					{
						var readTask = result.Content.ReadAsAsync<Item>();
						readTask.Wait();

						item = readTask.Result;
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
			}
			return View(item);
		}

		// POST: Items/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[AllowAnonymous]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Category,Description,Price")] Item item)
		{
			if (SessionWrapper.role != 1)
			{
				ModelState.AddModelError(string.Empty, "Access Denied. Only available to admin");
				return RedirectToAction(nameof(Index));

			}

			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					var response = await client.PutAsJsonAsync<Item>("http://localhost:5000/api/items/" + id, item);
					if (response.IsSuccessStatusCode)
					{
						var retVal = await response.Content.ReadAsAsync<Item>();
						return RedirectToAction("Details", new { id = retVal.Id });
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
				return View(item);
			}
		}

		// GET: Items/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			Item item = null;
			if (SessionWrapper.role != 1)
			{
				ModelState.AddModelError(string.Empty, "Access Denied. Only available to admin");
				return View(item);
			}

			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					var responseTask = client.GetAsync("http://localhost:5000/api/items/" + id);
					responseTask.Wait();

					var result = responseTask.Result;
					if (result.IsSuccessStatusCode)
					{
						var readTask = result.Content.ReadAsAsync<Item>();
						readTask.Wait();

						item = readTask.Result;
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
			}
			return View(item);
		}

		// POST: Items/Delete/5
		[AllowAnonymous]
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (SessionWrapper.role != 1)
			{
				ModelState.AddModelError(string.Empty, "Access Denied. Only available to admin");
				return RedirectToAction(nameof(Index));
			}

			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.BaseAddress = new Uri("http://localhost:5000/api/");
					client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					var response = await client.DeleteAsync("items/" + id);

					if (response.IsSuccessStatusCode)
					{
						var retVal = await response.Content.ReadAsAsync<Item>();
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
			};
			return RedirectToAction(nameof(Index));
		}
	}
}

HotelMVC/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HotelMVC_TONE.Models;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Net.Http.Headers;

namespace HotelMVC_TONE.Controllers
{
	public class OrdersController : Controller
	{

		public override void OnActionExecuting(ActionExecutingContext filterContext)
		{
			if (SessionWrapper.userId == -1)
			{
				RedirectToAction("Index");
			}
		}

		// GET: Orders
		public async Task<IActionResult> Index()
		{
			IEnumerable<Orders> orderItems = null;

			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					//HTTP GET item list
					//client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);
					client.DefaultRequestHeaders.Add("Authorization", "Bearer " + SessionWrapper.token);

					string path;
					if (SessionWrapper.role != 1)
						path = "http://localhost:5000/api/orders/list/" + SessionWrapper.userId;
					else
						path = "http://localhost:5000/api/orders/list";

					var responseTask = client.GetAsync(path);
					responseTask.Wait();

					var result = responseTask.Result;
					if (result.IsSuccessStatusCode)
					{
						var readTask = result.Content.ReadAsAsync<IList<Orders>>();
						readTask.Wait();

						orderItems = readTask.Result;
					}
					else
					{
						orderItems = Enumerable.Empty<Orders>();

						ModelState.AddModelError(string.Empty, "Server error.");
					}

					Dictionary<int, decimal> cartTotals = new Dictionary<int, decimal>();
					List<Tuple<int, string>> orders = new List<Tuple<int, string>>();

					foreach (Orders o in orderItems)
					{
						if (cartTotals.ContainsKey(o.orderId))
						{
							cartTotals[o.orderId] += o.price * o.quantity;
						}
						else
						{
							cartTotals[o.orderId] = o.price * o.quantity;
						}
						orders.Add(new Tuple<int, string>(o.orderId, o.dop.ToLongDateString()));
					}
					return View(new Tuple<List<Tuple<int, string>>, Dictionary<int, decimal>>(orders.Distinct().ToList(), cartTotals));
				}
			}
		}

		// GET: Orders/Details/5

		public async Task<IActionResult> Details(int? id)
		{
			IEnumerable<OrderItem> orderItems = null;

			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					var responseTask = client.GetAsync("http://localhost:5000/api/orders/" + id);
					responseTask.Wait();

					var result = responseTask.Result;
					if (result.IsSuccessStatusCode)
					{
						var readTask = result.Content.ReadAsAsync<IEnumerable<OrderItem>>();
						readTask.Wait();

						orderItems = readTask.Result;
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
			}
			return View(orderItems);
		}

		// POST: Orders/Edit/5

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,orderId,userId,itemId,price,quantity")] Orders order)
		{
			try
			{
				if (SessionWrapper.role != 1)
				{
					ModelState.AddModelError(string.Empty, "Access Denied. Only available to admin");
					return RedirectToAction(nameof(Index));
				}
				using (var httpClientHandler = new HttpClientHandler())
				{
					httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

					using (var client = new HttpClient(httpClientHandler))
					{
						client.BaseAddress = new Uri("http://localhost:5000/api/");
						client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
						client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

						var response = await client.PutAsJsonAsync<Orders>("orders/" + id, order);
						if (response.IsSuccessStatusCode)
						{
							var retVal = await response.Content.ReadAsAsync<Orders>();
							ViewBag.Message = "Profile updated";
							return RedirectToAction("Details", new { id = retVal.Id });
						}
						else
						{
							ModelState.AddModelError(string.Empty, "Server error.");
							return View(order);
						}
					}
				}
			}
			catch
			{
				return View();
			}
		}

		// GET: Orders/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			Orders order = null;

			if (SessionWrapper.role != 1)
			{
				ModelState.AddModelError(string.Empty, "Access Denied. Only available to admin");
				return View(order);
			}

			using (var httpClientHandler = new HttpClientHandler())
			{
				httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

				using (var client = new HttpClient(httpClientHandler))
				{
					client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

					var responseTask = client.GetAsync("http://localhost:5000/api/orders/" + id);
					responseTask.Wait();

					var result = responseTask.Result;
					if (result.IsSuccessStatusCode)
					{
						var readTask = result.Content.ReadAsAsync<Orders>();
						readTask.Wait();

						order = readTask.Result;
					}
					else
					{
						ModelState.AddModelError(string.Empty, "Server error.");
					}
				}
			}
			return View(order);
		}

		// POST: Orders/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(int id, [Bind("Id,orderId,userId,itemId,price,quantity")] Orders order)
		{
			try
			{
				if (SessionWrapper.role != 1)
				{
					ModelState.AddModelError(string.Empty, "Access Denied. Only available to admin");
					return RedirectToAction(nameof(Index));

				}

				using (var httpClientHandler = new HttpClientHandler())
				{
					httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };

					using (var client = new HttpClient(httpClientHandler))
					{
						client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
						client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", SessionWrapper.token);

						var response = await client.DeleteAsync("http://localhost:5000/api/orders/" + id);
						if (response.IsSuccessStatusCode)
						{
							var retVal = await response.Content.ReadAsAsync<Orders>();
							return RedirectToAction("Index");
						}
						else
						{
							ModelState.AddModelError(string.Empty, "Server error.");
						}
					}
					return View(order);
				}
			}
			catch
			{
				return View();
			}
		}

		//private bool OrderExists(int id)
		//{
		//	return _context.Order.Any(e => e.Id == id);
		//}
	}
}

HotelMVC/Views/Orders/Delete.cshtml
@model HotelMVC_TONE.Models.Orders

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.userId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.itemId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.itemId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

HotelMVC/Views/Orders/Details.cshtml
@model IEnumerable<OrderItem>
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Details</title>
</head>
<body>
	<table class="table">
		<thead>
			<tr>
				<th>
					Order Id#
				</th>
				<th>
					Title
				</th>
				<th>
					Price
				</th>
				<th>
					Quantity
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.order.orderId)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.item.Title)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.item.Price)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.order.quantity)
					</td>
					<td>
						<a asp-action="Details" asp-controller="Items" asp-route-id="@item.item.Id">Details</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</body>
</html>

HotelMVC/Views/Orders/Edit.cshtml
@model HotelMVC_TONE.Models.Orders
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="userId" class="control-label"></label>
                <input asp-for="userId" class="form-control" />
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="itemId" class="control-label"></label>
                <input asp-for="itemId" class="form-control" />
                <span asp-validation-for="itemId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

HotelMVC/Views/Orders/Index.cshtml
@model Tuple<List<Tuple<int, string>>, Dictionary<int, decimal>>

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Index</title>
</head>
<body>
	<table class="table">
		<thead>
			<tr>
				<th>
					Order Id#
				</th>
				<th>
					Total
				</th>
				<th>
					Date of Purchase
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Item1)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Item1)
					</td>
					<td>
						@Html.DisplayFor(modelItem => Model.Item2[item.Item1])
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Item2)
					</td>
					<td>
						<a asp-action="Edit" asp-route-id="@item.Item1">Edit</a> |
						<a asp-action="Details" asp-route-id="@item.Item1">Details</a> |
						<a asp-action="Delete" asp-route-id="@item.Item1">Delete</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</body>
</html>